name: build
on:
  push:
    branches:
      - master
env:
  ALIYUN_DOCKER_USERNAME: ${{secrets.ALIYUN_DOCKER_USERNAME}}
  ALIYUN_DOCKER_PASSWORD: ${{secrets.ALIYUN_DOCKER_PASSWORD}}
jobs:
  alpine:
    name: alpine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh alpine
  alpine-glibc:
    name: alpine-glibc
    runs-on: ubuntu-latest
    needs:
      - alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh alpine-glibc
  alpine-glibc-grpc:
    name: alpine-glibc-grpc
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh alpine-glibc-grpc
  ci-bot:
    name: ci-bot
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh ci-bot
  ci-mysql:
    name: ci-mysql
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh ci-mysql
  ci-tidb:
    name: ci-tidb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh ci-tidb
  go-dev:
    name: go-dev
    runs-on: ubuntu-latest
    needs:
      - alpine-glibc-grpc
      - ci-bot
      - protogen
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh go-dev
  node:
    name: node
    runs-on: ubuntu-latest
    needs:
      - protogen
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh node
  protogen:
    name: protogen
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: sh build.sh protogen
